version: "3.3"

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042" # CQL port
    volumes:
      - scylla-data:/var/lib/scylla

volumes:
  scylla-data:
